import { DefaultTheme } from '@react-navigation/native';

const Light = {
  ...DefaultTheme,
  fonts: {
    Roboto: 'Roboto',
    RobotoMedium: 'RobotoMedium',
    ProductSansRegular: 'ProductSansRegular',
    ProductSansLight: 'ProductSansLight',
    ProductSansBold: 'ProductSansBold',
    ProductSansMedium: 'ProductSansMedium',
    RubikRegular: "RubikRegular",
    RubikMedium: "RubikMedium",
    RubikLight: "RubikLight",
    RubikItalic: "RubikItalic",
    RubikBold: "RubikBold",
    LemonadaRegular: "LemonadaRegular",
    LemonadaMedium: "LemonadaMedium",
    LemonadaLight: "LemonadaLight",
    LemonadaSemiBold: "LemonadaSemiBold",
    FuturaRegular: "FuturaRegular",
    FuturaMedium: 'FuturaMedium',
    FuturaLight: "FuturaLight",
    FuturaItalic: "FuturaItalic",
    FuturaBold: "FuturaBold",
  },
  fontSizes: {
    body: 16,
    heading: 24,
    title: 33,
    small: 14,
    cardTitle: 18,
    iconSize: 22,
  },
  colors: {
    ...DefaultTheme.colors,
    light: '#f8f8f9',
    danger: '#ff3d71',
    info: '#0095ff',
    gray: 'gray',
    purple: '#673ab7',
    navy: '#093892',
    success: '#00d68f',
    white: '#ffffff',
    background: '#fff',
    warn: '#e9b21c',
    dark: '#101f3d',
    black: '#121212',
    active: '#e9b21c',
    text: '#101f3d',
    primary: '#e9b21c',
    appBar: '#121212',
    onAppBar: '#ffffff',
    surface: '#f0f3f5',
    secondary: '#b79cff',
    onBackground: '#000',
    onSurface: '#000',
    onPrimary: '#fff',
    borderColor: '#f0f3f5',
    onSecondary: '#000',
    statusBar: 'light-content',
    transparent: 'transparent',
    transparentInput: 'rgba(255,255,255, .30)',
  },
};

export default Light;
