import { DefaultTheme } from '@react-navigation/native';

const Light = {
  ...DefaultTheme,
  fonts: {
    Roboto: 'Roboto',
    RobotoMedium: 'RobotoMedium',
    ProductSansRegular: 'ProductSansRegular',
    ProductSansLight: 'ProductSansLight',
    ProductSansBold: 'ProductSansBold',
    ProductSansMedium: 'ProductSansMedium',
    RubikRegular: "RubikRegular",
    RubikMedium: "RubikMedium",
    RubikLight: "RubikLight",
    RubikItalic: "RubikItalic",
    RubikBold: "RubikBold",
    LemonadaRegular: "LemonadaRegular",
    LemonadaMedium: "LemonadaMedium",
    LemonadaLight: "LemonadaLight",
    LemonadaSemiBold: "LemonadaSemiBold",
  },
  fontSizes: {
    body: 18,
    heading: 26,
    title: 35,
    small: 16,
    iconSize: 22,
  },
  colors: {
    ...DefaultTheme.colors,
    light: 'lightgray',
    danger: '#ff3d71',
    info: '#0095ff',
    purple: '#816dff',
    success: '#00d68f',
    white: '#ffffff',
    background: '#fff',
    warn: '#F8B51F',
    dark: '#282828',
    black: '#000000',
    active: '#974578',
    text: '#282828',
    primary: '#974578',
    appBar: '#67164c',
    onAppBar: '#ffffff',
    surface: '#f0f3f5',
    secondary: '#b79cff',
    onBackground: '#000',
    onSurface: '#000',
    onPrimary: '#fff',
    borderColor: '#f0f3f5',
    onSecondary: '#000',
    statusBar: 'light-content',
    transparent: 'transparent',
    transparentInput: 'rgba(255,255,255, .30)',
  },
};

export default Light;
